#!/bin/bash -e

jisonStdout=$(npx jison vault.jison)

if [ ${#jisonStdout} -gt 0 ]; then
  echo "$jisonStdout" 1>&2
  exit 1
fi

echo "import { Syntax } from './parse';" >testProgram.ts
echo >>testProgram.ts
echo "export const testProgram: Syntax.Program =" >>testProgram.ts
DEPTH=100 PRINT=1 node vault.js input.vlt >>testProgram.ts
echo ";" >>testProgram.ts
